[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.16"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.7.0"

[[constraint]]
  name = "github.com/eximchain/go-ethereum"
  branch = "master"

[[constraint]]
  name = "github.com/eximchain/eth-client"
  branch = "master"

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "0.11.2"

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
      name = "github.com/eximchain/go-ethereum"
      unused-packages = false
